title: Mr Dinev's Classes
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mrdinev.github.io/classes

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
