title: Mr Dinev's Classes
description: On this site you can find all the lesson plans for your subject. 
theme: just-the-docs

url: https://mrdinev.github.io/classes

aux_links:
  Compass: https://heathmont-vic.compass.education
  
# Define Jekyll collections
collections:
  tests:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
      nav_fold: false
    tutorials:
      name: Tutorials
      nav_fold: true
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

# callouts
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
      
