title: Mr Dinev's Classes
description: On this site you can find all the lesson plans for your subject. 
theme: just-the-docs

url: https://mrdinev.github.io/classes

aux_links:
  Compass: https://heathmont-vic.compass.education
  
